
#all:  gamow-06-test.inc font2b

#gamow-06-test.inc: gamow-06-test-m-r.psfu
#	psf2inc gamow-06-test-m-r.psfu >gamow-06-test.inc


font2b: font2b.c  
	gcc -O2 -Wall font2b.c -o font2b


clean:
	rm -f *.o  *~ font2b 

### EOF
